//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>About - Page</summary>
	[PublishedModel("aboutPage")]
	public partial class AboutPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "aboutPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<AboutPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public AboutPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// aboutBkgImg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBkgImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBkgImg => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBkgImg");

		///<summary>
		/// aboutHomeLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutHomeLink")]
		public virtual string AboutHomeLink => this.Value<string>(_publishedValueFallback, "aboutHomeLink");

		///<summary>
		/// aboutLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutLink")]
		public virtual string AboutLink => this.Value<string>(_publishedValueFallback, "aboutLink");

		///<summary>
		/// aboutUsHeadline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsHeadline")]
		public virtual string AboutUsHeadline => this.Value<string>(_publishedValueFallback, "aboutUsHeadline");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// projectEmail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectEmail")]
		public virtual string ProjectEmail => this.Value<string>(_publishedValueFallback, "projectEmail");

		///<summary>
		/// projectEmailText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectEmailText")]
		public virtual string ProjectEmailText => this.Value<string>(_publishedValueFallback, "projectEmailText");

		///<summary>
		/// projectHeadline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectHeadline")]
		public virtual string ProjectHeadline => this.Value<string>(_publishedValueFallback, "projectHeadline");

		///<summary>
		/// projectImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectImage");

		///<summary>
		/// projectLocation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectLocation")]
		public virtual string ProjectLocation => this.Value<string>(_publishedValueFallback, "projectLocation");

		///<summary>
		/// projectLocationText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectLocationText")]
		public virtual string ProjectLocationText => this.Value<string>(_publishedValueFallback, "projectLocationText");

		///<summary>
		/// ProjectNumber
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectNumber")]
		public virtual string ProjectNumber => this.Value<string>(_publishedValueFallback, "projectNumber");

		///<summary>
		/// projectNumberText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectNumberText")]
		public virtual string ProjectNumberText => this.Value<string>(_publishedValueFallback, "projectNumberText");

		///<summary>
		/// reviewsHeadline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsHeadline")]
		public virtual string ReviewsHeadline => this.Value<string>(_publishedValueFallback, "reviewsHeadline");

		///<summary>
		/// reviewsHeadline-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsHeadline2")]
		public virtual string ReviewsHeadline2 => this.Value<string>(_publishedValueFallback, "reviewsHeadline2");

		///<summary>
		/// reviewsKevinImg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsKevinImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ReviewsKevinImg => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "reviewsKevinImg");

		///<summary>
		/// reviewsQuote
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsQuote")]
		public virtual string ReviewsQuote => this.Value<string>(_publishedValueFallback, "reviewsQuote");

		///<summary>
		/// reviewsRatingImg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsRatingImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ReviewsRatingImg => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "reviewsRatingImg");

		///<summary>
		/// reviewsText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsText")]
		public virtual string ReviewsText => this.Value<string>(_publishedValueFallback, "reviewsText");

		///<summary>
		/// reviewsTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsTitle")]
		public virtual string ReviewsTitle => this.Value<string>(_publishedValueFallback, "reviewsTitle");

		///<summary>
		/// storyImg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops StoryImg => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "storyImg");

		///<summary>
		/// storyQuote
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyQuote")]
		public virtual string StoryQuote => this.Value<string>(_publishedValueFallback, "storyQuote");

		///<summary>
		/// storyText-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyText1")]
		public virtual string StoryText1 => this.Value<string>(_publishedValueFallback, "storyText1");

		///<summary>
		/// storyText-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyText2")]
		public virtual string StoryText2 => this.Value<string>(_publishedValueFallback, "storyText2");

		///<summary>
		/// storyText-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyText3")]
		public virtual string StoryText3 => this.Value<string>(_publishedValueFallback, "storyText3");

		///<summary>
		/// storyText-4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyText4")]
		public virtual string StoryText4 => this.Value<string>(_publishedValueFallback, "storyText4");

		///<summary>
		/// storyText-5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyText5")]
		public virtual string StoryText5 => this.Value<string>(_publishedValueFallback, "storyText5");

		///<summary>
		/// storyText-6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyText6")]
		public virtual string StoryText6 => this.Value<string>(_publishedValueFallback, "storyText6");

		///<summary>
		/// storyText-7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyText7")]
		public virtual string StoryText7 => this.Value<string>(_publishedValueFallback, "storyText7");

		///<summary>
		/// storytText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storytText")]
		public virtual string StorytText => this.Value<string>(_publishedValueFallback, "storytText");

		///<summary>
		/// teamsBoxHeadline-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxHeadline1")]
		public virtual string TeamsBoxHeadline1 => this.Value<string>(_publishedValueFallback, "teamsBoxHeadline1");

		///<summary>
		/// teamsBoxHeadline-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxHeadline2")]
		public virtual string TeamsBoxHeadline2 => this.Value<string>(_publishedValueFallback, "teamsBoxHeadline2");

		///<summary>
		/// teamsBoxHeadline-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxHeadline3")]
		public virtual string TeamsBoxHeadline3 => this.Value<string>(_publishedValueFallback, "teamsBoxHeadline3");

		///<summary>
		/// teamsBoxHeadline-4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxHeadline4")]
		public virtual string TeamsBoxHeadline4 => this.Value<string>(_publishedValueFallback, "teamsBoxHeadline4");

		///<summary>
		/// teamsBoxHeadline-5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxHeadline5")]
		public virtual string TeamsBoxHeadline5 => this.Value<string>(_publishedValueFallback, "teamsBoxHeadline5");

		///<summary>
		/// teamsBoxHeadline-6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxHeadline6")]
		public virtual string TeamsBoxHeadline6 => this.Value<string>(_publishedValueFallback, "teamsBoxHeadline6");

		///<summary>
		/// teamsBoxHeadline-7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxHeadline7")]
		public virtual string TeamsBoxHeadline7 => this.Value<string>(_publishedValueFallback, "teamsBoxHeadline7");

		///<summary>
		/// teamsBoxImage-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxImage1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamsBoxImage1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamsBoxImage1");

		///<summary>
		/// teamsBoxImage-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxImage2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamsBoxImage2 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamsBoxImage2");

		///<summary>
		/// teamsBoxImage-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxImage3")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamsBoxImage3 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamsBoxImage3");

		///<summary>
		/// teamsBoxImage-4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxImage4")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamsBoxImage4 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamsBoxImage4");

		///<summary>
		/// teamsBoxImage-5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxImage5")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamsBoxImage5 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamsBoxImage5");

		///<summary>
		/// teamsBoxImage-6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxImage6")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamsBoxImage6 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamsBoxImage6");

		///<summary>
		/// teamsBoxImage-7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxImage7")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TeamsBoxImage7 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "teamsBoxImage7");

		///<summary>
		/// teamsBoxText-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxText1")]
		public virtual string TeamsBoxText1 => this.Value<string>(_publishedValueFallback, "teamsBoxText1");

		///<summary>
		/// teamsBoxText-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxText2")]
		public virtual string TeamsBoxText2 => this.Value<string>(_publishedValueFallback, "teamsBoxText2");

		///<summary>
		/// teamsBoxText-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxText3")]
		public virtual string TeamsBoxText3 => this.Value<string>(_publishedValueFallback, "teamsBoxText3");

		///<summary>
		/// teamsBoxText-4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxText4")]
		public virtual string TeamsBoxText4 => this.Value<string>(_publishedValueFallback, "teamsBoxText4");

		///<summary>
		/// teamsBoxText-5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxText5")]
		public virtual string TeamsBoxText5 => this.Value<string>(_publishedValueFallback, "teamsBoxText5");

		///<summary>
		/// teamsBoxText-6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxText6")]
		public virtual string TeamsBoxText6 => this.Value<string>(_publishedValueFallback, "teamsBoxText6");

		///<summary>
		/// teamsBoxText-7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsBoxText7")]
		public virtual string TeamsBoxText7 => this.Value<string>(_publishedValueFallback, "teamsBoxText7");

		///<summary>
		/// teamsHeadline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsHeadline")]
		public virtual string TeamsHeadline => this.Value<string>(_publishedValueFallback, "teamsHeadline");

		///<summary>
		/// teamsTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("teamsTitle")]
		public virtual string TeamsTitle => this.Value<string>(_publishedValueFallback, "teamsTitle");
	}
}
