//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Projects - Page</summary>
	[PublishedModel("projectsPage")]
	public partial class ProjectsPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "projectsPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ProjectsPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ProjectsPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// projectContactHeadline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactHeadline")]
		public virtual string ProjectContactHeadline => this.Value<string>(_publishedValueFallback, "projectContactHeadline");

		///<summary>
		/// projectContactImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectContactImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectContactImage");

		///<summary>
		/// projectContactText-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactText1")]
		public virtual string ProjectContactText1 => this.Value<string>(_publishedValueFallback, "projectContactText1");

		///<summary>
		/// projectContactText-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactText2")]
		public virtual string ProjectContactText2 => this.Value<string>(_publishedValueFallback, "projectContactText2");

		///<summary>
		/// projectContactText-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactText3")]
		public virtual string ProjectContactText3 => this.Value<string>(_publishedValueFallback, "projectContactText3");

		///<summary>
		/// projectContactText-4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactText4")]
		public virtual string ProjectContactText4 => this.Value<string>(_publishedValueFallback, "projectContactText4");

		///<summary>
		/// projectContactText-5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactText5")]
		public virtual string ProjectContactText5 => this.Value<string>(_publishedValueFallback, "projectContactText5");

		///<summary>
		/// projectContactText-6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContactText6")]
		public virtual string ProjectContactText6 => this.Value<string>(_publishedValueFallback, "projectContactText6");

		///<summary>
		/// projectContentHeadline-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentHeadline1")]
		public virtual string ProjectContentHeadline1 => this.Value<string>(_publishedValueFallback, "projectContentHeadline1");

		///<summary>
		/// projectContentHeadline-10
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentHeadline10")]
		public virtual string ProjectContentHeadline10 => this.Value<string>(_publishedValueFallback, "projectContentHeadline10");

		///<summary>
		/// projectContentHeadline-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentHeadline2")]
		public virtual string ProjectContentHeadline2 => this.Value<string>(_publishedValueFallback, "projectContentHeadline2");

		///<summary>
		/// projectContentHeadline-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentHeadline3")]
		public virtual string ProjectContentHeadline3 => this.Value<string>(_publishedValueFallback, "projectContentHeadline3");

		///<summary>
		/// projectContentHeadline-4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentHeadline4")]
		public virtual string ProjectContentHeadline4 => this.Value<string>(_publishedValueFallback, "projectContentHeadline4");

		///<summary>
		/// projectContentHeadline-5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentHeadline5")]
		public virtual string ProjectContentHeadline5 => this.Value<string>(_publishedValueFallback, "projectContentHeadline5");

		///<summary>
		/// projectContentHeadline-6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentHeadline6")]
		public virtual string ProjectContentHeadline6 => this.Value<string>(_publishedValueFallback, "projectContentHeadline6");

		///<summary>
		/// projectContentHeadline-7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentHeadline7")]
		public virtual string ProjectContentHeadline7 => this.Value<string>(_publishedValueFallback, "projectContentHeadline7");

		///<summary>
		/// projectContentHeadline-8
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentHeadline8")]
		public virtual string ProjectContentHeadline8 => this.Value<string>(_publishedValueFallback, "projectContentHeadline8");

		///<summary>
		/// projectContentHeadline-9
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentHeadline9")]
		public virtual string ProjectContentHeadline9 => this.Value<string>(_publishedValueFallback, "projectContentHeadline9");

		///<summary>
		/// projectContentImage-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentImage1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectContentImage1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectContentImage1");

		///<summary>
		/// projectContentImage-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentImage2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectContentImage2 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectContentImage2");

		///<summary>
		/// projectContentImage-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentImage3")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectContentImage3 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectContentImage3");

		///<summary>
		/// projectContentImage-4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentImage4")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectContentImage4 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectContentImage4");

		///<summary>
		/// projectContentText-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText1")]
		public virtual string ProjectContentText1 => this.Value<string>(_publishedValueFallback, "projectContentText1");

		///<summary>
		/// projectContentText-10
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText10")]
		public virtual string ProjectContentText10 => this.Value<string>(_publishedValueFallback, "projectContentText10");

		///<summary>
		/// projectContentText-11
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText11")]
		public virtual string ProjectContentText11 => this.Value<string>(_publishedValueFallback, "projectContentText11");

		///<summary>
		/// projectContentText-12
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText12")]
		public virtual string ProjectContentText12 => this.Value<string>(_publishedValueFallback, "projectContentText12");

		///<summary>
		/// projectContentText-13
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText13")]
		public virtual string ProjectContentText13 => this.Value<string>(_publishedValueFallback, "projectContentText13");

		///<summary>
		/// projectContentText-14
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText14")]
		public virtual string ProjectContentText14 => this.Value<string>(_publishedValueFallback, "projectContentText14");

		///<summary>
		/// projectContentText-15
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText15")]
		public virtual string ProjectContentText15 => this.Value<string>(_publishedValueFallback, "projectContentText15");

		///<summary>
		/// projectContentText-16
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText16")]
		public virtual string ProjectContentText16 => this.Value<string>(_publishedValueFallback, "projectContentText16");

		///<summary>
		/// projectContentText-17
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText17")]
		public virtual string ProjectContentText17 => this.Value<string>(_publishedValueFallback, "projectContentText17");

		///<summary>
		/// projectContentText-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText2")]
		public virtual string ProjectContentText2 => this.Value<string>(_publishedValueFallback, "projectContentText2");

		///<summary>
		/// projectContentText-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText3")]
		public virtual string ProjectContentText3 => this.Value<string>(_publishedValueFallback, "projectContentText3");

		///<summary>
		/// projectContentText-4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText4")]
		public virtual string ProjectContentText4 => this.Value<string>(_publishedValueFallback, "projectContentText4");

		///<summary>
		/// projectContentText-5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText5")]
		public virtual string ProjectContentText5 => this.Value<string>(_publishedValueFallback, "projectContentText5");

		///<summary>
		/// projectContentText-6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText6")]
		public virtual string ProjectContentText6 => this.Value<string>(_publishedValueFallback, "projectContentText6");

		///<summary>
		/// projectContentText-7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText7")]
		public virtual string ProjectContentText7 => this.Value<string>(_publishedValueFallback, "projectContentText7");

		///<summary>
		/// projectContentText-8
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText8")]
		public virtual string ProjectContentText8 => this.Value<string>(_publishedValueFallback, "projectContentText8");

		///<summary>
		/// projectContentText-9
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectContentText9")]
		public virtual string ProjectContentText9 => this.Value<string>(_publishedValueFallback, "projectContentText9");

		///<summary>
		/// projectsLinkHome
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectsLinkHome")]
		public virtual string ProjectsLinkHome => this.Value<string>(_publishedValueFallback, "projectsLinkHome");

		///<summary>
		/// projectsLinkServices
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectsLinkServices")]
		public virtual string ProjectsLinkServices => this.Value<string>(_publishedValueFallback, "projectsLinkServices");

		///<summary>
		/// projectsMainHeadline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectsMainHeadline")]
		public virtual string ProjectsMainHeadline => this.Value<string>(_publishedValueFallback, "projectsMainHeadline");

		///<summary>
		/// projectsMainImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectsMainImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectsMainImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectsMainImage");
	}
}
