//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Project - Details</summary>
	[PublishedModel("projectDetails")]
	public partial class ProjectDetails : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "projectDetails";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ProjectDetails, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ProjectDetails(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// projectDetailsContentHeadline-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentHeadline1")]
		public virtual string ProjectDetailsContentHeadline1 => this.Value<string>(_publishedValueFallback, "projectDetailsContentHeadline1");

		///<summary>
		/// projectDetailsContentHeadline-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentHeadline2")]
		public virtual string ProjectDetailsContentHeadline2 => this.Value<string>(_publishedValueFallback, "projectDetailsContentHeadline2");

		///<summary>
		/// projectDetailsContentHeadline-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentHeadline3")]
		public virtual string ProjectDetailsContentHeadline3 => this.Value<string>(_publishedValueFallback, "projectDetailsContentHeadline3");

		///<summary>
		/// projectDetailsContentHeadline-4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentHeadline4")]
		public virtual string ProjectDetailsContentHeadline4 => this.Value<string>(_publishedValueFallback, "projectDetailsContentHeadline4");

		///<summary>
		/// projectDetailsContentHeadline-5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentHeadline5")]
		public virtual string ProjectDetailsContentHeadline5 => this.Value<string>(_publishedValueFallback, "projectDetailsContentHeadline5");

		///<summary>
		/// projectDetailsContentHeadline-6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentHeadline6")]
		public virtual string ProjectDetailsContentHeadline6 => this.Value<string>(_publishedValueFallback, "projectDetailsContentHeadline6");

		///<summary>
		/// projectDetailsContentHeadline-7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentHeadline7")]
		public virtual string ProjectDetailsContentHeadline7 => this.Value<string>(_publishedValueFallback, "projectDetailsContentHeadline7");

		///<summary>
		/// projectDetailsContentHeadline-8
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentHeadline8")]
		public virtual string ProjectDetailsContentHeadline8 => this.Value<string>(_publishedValueFallback, "projectDetailsContentHeadline8");

		///<summary>
		/// projectDetailsContentImg-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentImg1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectDetailsContentImg1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectDetailsContentImg1");

		///<summary>
		/// projectDetailsContentImg-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentImg2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectDetailsContentImg2 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectDetailsContentImg2");

		///<summary>
		/// projectDetailsContentImg-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentImg3")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectDetailsContentImg3 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectDetailsContentImg3");

		///<summary>
		/// projectDetailsContentText-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText1")]
		public virtual string ProjectDetailsContentText1 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText1");

		///<summary>
		/// projectDetailsContentText-10
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText10")]
		public virtual string ProjectDetailsContentText10 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText10");

		///<summary>
		/// projectDetailsContentText-11
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText11")]
		public virtual string ProjectDetailsContentText11 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText11");

		///<summary>
		/// projectDetailsContentText-12
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText12")]
		public virtual string ProjectDetailsContentText12 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText12");

		///<summary>
		/// projectDetailsContentText-13
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText13")]
		public virtual string ProjectDetailsContentText13 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText13");

		///<summary>
		/// projectDetailsContentText-14
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText14")]
		public virtual string ProjectDetailsContentText14 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText14");

		///<summary>
		/// projectDetailsContentText-15
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText15")]
		public virtual string ProjectDetailsContentText15 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText15");

		///<summary>
		/// projectDetailsContentText-16
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText16")]
		public virtual string ProjectDetailsContentText16 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText16");

		///<summary>
		/// projectDetailsContentText-17
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText17")]
		public virtual string ProjectDetailsContentText17 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText17");

		///<summary>
		/// projectDetailsContentText-18
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText18")]
		public virtual string ProjectDetailsContentText18 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText18");

		///<summary>
		/// projectDetailsContentText-19
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText19")]
		public virtual string ProjectDetailsContentText19 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText19");

		///<summary>
		/// projectDetailsContentText-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText2")]
		public virtual string ProjectDetailsContentText2 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText2");

		///<summary>
		/// projectDetailsContentText-20
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText20")]
		public virtual string ProjectDetailsContentText20 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText20");

		///<summary>
		/// projectDetailsContentText-21
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText21")]
		public virtual string ProjectDetailsContentText21 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText21");

		///<summary>
		/// projectDetailsContentText-22
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText22")]
		public virtual string ProjectDetailsContentText22 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText22");

		///<summary>
		/// projectDetailsContentText-23
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText23")]
		public virtual string ProjectDetailsContentText23 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText23");

		///<summary>
		/// projectDetailsContentText-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText3")]
		public virtual string ProjectDetailsContentText3 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText3");

		///<summary>
		/// projectDetailsContentText-4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText4")]
		public virtual string ProjectDetailsContentText4 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText4");

		///<summary>
		/// projectDetailsContentText-5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText5")]
		public virtual string ProjectDetailsContentText5 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText5");

		///<summary>
		/// projectDetailsContentText-6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText6")]
		public virtual string ProjectDetailsContentText6 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText6");

		///<summary>
		/// projectDetailsContentText-7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText7")]
		public virtual string ProjectDetailsContentText7 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText7");

		///<summary>
		/// projectDetailsContentText-8
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText8")]
		public virtual string ProjectDetailsContentText8 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText8");

		///<summary>
		/// projectDetailsContentText-9
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsContentText9")]
		public virtual string ProjectDetailsContentText9 => this.Value<string>(_publishedValueFallback, "projectDetailsContentText9");

		///<summary>
		/// projectDetailsImage-project
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsImageProject")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectDetailsImageProject => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectDetailsImageProject");

		///<summary>
		/// projectDetailsMainHeadline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsMainHeadline")]
		public virtual string ProjectDetailsMainHeadline => this.Value<string>(_publishedValueFallback, "projectDetailsMainHeadline");

		///<summary>
		/// projectDetailsMainImg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsMainImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectDetailsMainImg => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectDetailsMainImg");

		///<summary>
		/// projectDetailsMaintext-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsMaintext1")]
		public virtual string ProjectDetailsMaintext1 => this.Value<string>(_publishedValueFallback, "projectDetailsMaintext1");

		///<summary>
		/// projectDetailsMaintext-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsMaintext2")]
		public virtual string ProjectDetailsMaintext2 => this.Value<string>(_publishedValueFallback, "projectDetailsMaintext2");

		///<summary>
		/// projectDetailsMaintext-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsMaintext3")]
		public virtual string ProjectDetailsMaintext3 => this.Value<string>(_publishedValueFallback, "projectDetailsMaintext3");

		///<summary>
		/// projectDetailsProjectHeadline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsProjectHeadline")]
		public virtual string ProjectDetailsProjectHeadline => this.Value<string>(_publishedValueFallback, "projectDetailsProjectHeadline");

		///<summary>
		/// projectDetailsProjectText-1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsProjectText1")]
		public virtual string ProjectDetailsProjectText1 => this.Value<string>(_publishedValueFallback, "projectDetailsProjectText1");

		///<summary>
		/// projectDetailsProjectText-2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsProjectText2")]
		public virtual string ProjectDetailsProjectText2 => this.Value<string>(_publishedValueFallback, "projectDetailsProjectText2");

		///<summary>
		/// projectDetailsProjectText-3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsProjectText3")]
		public virtual string ProjectDetailsProjectText3 => this.Value<string>(_publishedValueFallback, "projectDetailsProjectText3");

		///<summary>
		/// projectDetailsProjectText-4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsProjectText4")]
		public virtual string ProjectDetailsProjectText4 => this.Value<string>(_publishedValueFallback, "projectDetailsProjectText4");

		///<summary>
		/// projectDetailsProjectText-5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsProjectText5")]
		public virtual string ProjectDetailsProjectText5 => this.Value<string>(_publishedValueFallback, "projectDetailsProjectText5");

		///<summary>
		/// projectDetailsProjectText-6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectDetailsProjectText6")]
		public virtual string ProjectDetailsProjectText6 => this.Value<string>(_publishedValueFallback, "projectDetailsProjectText6");
	}
}
